<?php

namespace SEstruch\WebsiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PinturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinturaRepository extends EntityRepository
{
}
