<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121111140311 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE texts (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, text_ca LONGTEXT NOT NULL, text_es LONGTEXT NOT NULL, text_en LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_1E3513BF5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("INSERT INTO texts SET name='biografia', text_ca='bio catala', text_es='bio castellano', text_en='bio english'");
        $this->addSql("INSERT INTO texts SET name='home', text_ca='home catala', text_es='home castellano', text_en='home english'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE texts");
    }
}
